openapi: 3.0.3
info:
  title: History Quiz
  version: "1"
paths:
  /api/v1/quiz:
    get:
      summary: Create a quiz - list of questions with answers
      description: creates quiz
      operationId: getQuiz
      tags:
        - quiz
      parameters:
        - name: numberOfQuestions
          in: query
          required: true
          schema:
            type: integer
          description: the number of questions in the quiz
        - name: numberOfAnswers
          in: query
          required: false
          schema:
            type: integer
          description: the number of available answers to choose
        - name: categories
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Quiz were generated
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "Question"
  /api/v1/categories:
    get:
      summary: Get all categories
      description: Returns a list of all categories
      operationId: getCategories
      tags:
        - Category
      responses:
        '200':
          description: All categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /admin/v1/questions/add:
    post:
      tags:
        - QuestionManagement
      summary: Add questions to the database
      description: Add questions to the database - with a json format
      operationId: addQuestions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "QuestionDB"
      responses:
        '202':
          description: Questions added to the database
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "ErrorDB"
        '406':
          description: One or more question cannot be added
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "ErrorDB"

components:
  schemas:
    Question:
      type: object
      properties:
        text:
          type: string
        correctAnswer:
          type: string
        otherAnswers:
          type: array
          items:
            type: string
    QuestionDB:
      type: object
      properties:
        questionText:
          type: string
        correctAnswer:
          type: string
        answerType:
          type: string
        period:
          type: string
        details:
          type: string
    ErrorDB:
      type: object
      properties:
        questionText:
          type: string
        reason:
          type: string
